#ifndef WVM_OPCODE_H
#define WVM_OPCODE_H

#include <stdint.h>

typedef enum opcode {
        NOP = 0,
        ADD = 1,
        SUB = 2,
        MUL = 3,
        DIV = 4,
        INC = 5,
        DEC = 6,
        JMP = 7,
        CMP = 8,
        JE = 9,
        JNE = 10,
        JL = 11,
        JG = 12,
        JLE = 13,
        JGE = 14,
        SETZ = 15,
        MOV = 16,
        LSH = 17,
        RSH = 18,
        LOAD = 19,
        STORE = 20,
        OR = 21,
        AND = 22,
        XOR = 23,
        TIME = 24,
        PUSH = 25,
        POP = 26,
        CALL = 27,
        RET = 28,
        EOP = 29,
        EOPV = 30,
        DEBUG = 31,
        LOOP = 32,
        ADD_LOOP_IMM = 33,
        INC_LOOP = 34,
        DEC_LOOP = 35,
        CMP_JE_IMM = 36,
        CMP_JNE_IMM = 37,
        CMP_JL_IMM = 38,
        CMP_JG_IMM = 39,
        CMP_JLE_IMM = 40,
        CMP_JGE_IMM = 41,
        MADD = 42,
        CMP_JE_REG = 43,
        CMP_JNE_REG = 44,
        CMP_JL_REG = 45,
        CMP_JG_REG = 46,
        CMP_JLE_REG = 47,
        CMP_JGE_REG = 48,
        INC_CMP_JL_IMM = 49,
        MOV_STORE_IMM = 50
} opcode_t;

#endif
